[package]
name = "pathobj"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env = { git = "https://github.com/sugarflowers/env.git" }
